import './globals.css';
import { Header } from './components/Header/Header';
import { theme } from '@/app/custom-styles/theme';
import { raleway } from './custom-styles/fonts';
import { ThemeProvider } from '@mui/material';
import type { Metadata } from 'next';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={raleway.className} suppressHydrationWarning={true}>
				<ThemeProvider theme={theme}>
					<Header />
					<main>{children}</main>
				</ThemeProvider>
			</body>
		</html>
	);
}
